config/routes.rb
Rails.application.routes.draw do
  resources :smena_shtrafs do
    collection { post :import }
  end

  resources :smena_rabs do
    collection { post :import }
  end

  resources :smenas do
    collection { post :import }
  end

  resources :perevods do
    collection { post :import }
  end

  resources :dohods do
    collection { post :import }
  end

  resources :rashods do
    collection { post :import }
  end

  resources :rab_images do
    collection { post :import }
  end

  resources :rabs do
    collection { post :import }
  end

  resources :schets do
    collection { post :import }
  end

  resources :cat_dohods do
    collection { post :import }
  end

  resources :cat_rashods do
    collection { post :import }
  end

  get 'dialog/index'

  resources :perevods

  resources :dohods

  resources :rashods

  resources :rab_images

  resources :rabs

  resources :schets

  resources :cat_dohods

  resources :cat_rashods

  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  devise_for :logins
  resources :logins
  resources :roles
  get 'home/index'
  root "home#index"

end

app/models/perevod.rb
class Perevod < ActiveRecord::Base
  include ActiveModel::Dirty
  validates :schet_from, presence: true
  validates :schet_to, presence: true

  # include TheSortableTree::Scopes
  # acts_as_nested_set

  # include FriendlyId
  # friendly_id :title, :use => [:slugged, :simple_i18n]

  # extend Enumerize
  # enumerize :some_field, in: [:one, "two", "last"]
  # locale.yml
  # enumerize:
  #   product:
  #     measure:
  #       gramm: "грамм"

  # has_and_belongs_to_many :events

  # audit table changes
  has_paper_trail
  # cattr_reader :per_page
  # @@per_page = 20
  # TODO paste it to Model Scaffold template  
  #cocoon_marker_start
  #cocoon_marker_data
  #cocoon_marker_end
  belongs_to :rab

  # before_save :perevoddo
  before_save :tocalc
  before_save :init_data
  # after_update :tochange
  after_destroy :tominus

  def self.import(file)
    spread = open_spreadsheet(file)
    spreadsheet = spread.sheet(0)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      perevod = find_by_id(row["id"]) || new
      perevod.update row.to_hash
      perevod.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |perevod|
        csv << perevod.attributes.values_at(*column_names)
      end
    end
  end

  define_method :name do
    "#{self.schet_from}"
  end

  def tocalc
      #self.cash
      from1=Schet.find(self.schet_from)
      from1.cash=from1.cash.to_f-self.cash.to_f
      from1.save

      to1=Schet.find(self.schet_to)
      to1.cash=to1.cash.to_f+self.cash.to_f
      to1.save
  end

  def tominus
  #   from2=Schet.find(self.schet_id)
  #   from2.cash=from2.cash.to_f-self.cash.to_f
  #   from2.save

    from2=Schet.find(self.schet_from)
    from2.cash=from2.cash.to_f+self.cash.to_f
    from2.save

    to1=Schet.find(self.schet_to)
    to1.cash=to1.cash.to_f-self.cash.to_f
    to1.save

  end

  def init_data
    self.todate ||= Date.today if new_record?
  end


end

app/controllers/perevods_controller.rb
class PerevodsController < ApplicationController
  before_action :set_perevod, only: [:show, :edit, :update, :destroy]
  ##before_action :redirect_tor

  def index
    @perevods = Perevod.all
    respond_with(@perevods)
  end

  def show
    respond_with(@perevod)
  end

  def new
    @perevod = Perevod.new
    respond_with(@perevod)
  end

  def edit
  end

  def create
    @perevod = Perevod.new(perevod_params)
    @perevod.save
    respond_with @perevod do |format|
      format.html { redirect_to root_path }
    end

  end

  def update
    @perevod.update(perevod_params)
    respond_with @perevod do |format|
      format.html { redirect_to root_path }
    end
  end

  def destroy
    @perevod.destroy
    respond_with @perevod do |format|
      format.html { redirect_to root_path }
    end
  end

  private
    def set_perevod
      @perevod = Perevod.find(params[:id])
    end

    def perevod_params
      params.require(:perevod).permit(:schet_from, :schet_to, :rab_id, :todate, :cash, :comment)
    end

    def redirect_tor
      respond_to do |format|
        format.html {redirect_to root_path}
        #format.js {render :js => "window.location.href='"+root_path+"'"} if params[:q].present?
      end
    end


end

app/views/perevods/_form.html.haml
= form_for @perevod, "data-ajax" => false do |f|
  - if @perevod.errors.any?
    #error_explanation
      %h2= "#{pluralize(@perevod.errors.count, "error")} prohibited this rab from being saved:"
      %ul
        - @perevod.errors.full_messages.each do |msg|
          %li= msg
  %div{ :class=>"schet_from"}
    .field
      = f.label t(:schet_from)
      = collection_select(:perevod, :schet_from, Schet.where(panel: true).all, :id, :name, prompt: true)

  %div{ :class=>"schet_to"}
    .field
      = f.label t(:schet_to)
      = collection_select(:perevod, :schet_to, Schet.where(panel: true).all, :id, :name, prompt: true)

  -#%div{ :class=>"rab"}
    -#.field
      -#= f.label t(:rab)
      -#= collection_select(:perevod, :rab_id, Rab.all, :id, :name, prompt: true)

  %div{ :class=>"todate"}
    .field
      = f.label t(:todate)
      = f.date_select :todate

  %div{ :class=>"cash"}
    .field
      = f.label t(:cash)
      = f.text_field :cash

  %div{ :class=>"comment"}
    .field
      = f.label t(:comment)
      = f.text_area :comment

      - 'TABB'
  %div
    .field
      = f.submit t('.save', :default => t("helpers.links.save")), :class => "btn btn-primary", "data-ajax" => false

app/views/perevods/destroy.js.haml
// Удаление

// Уведомление 
var perevod_#{@perevod_id} = function(){ new PNotify({ title: "Запись #{@perevod.name} удалена.", type: 'error', icon: false, hide: true, delay: 1500, buttons: { sticker: false } })};
perevod_#{@perevod_id}();

// Удаление из dataTables
$("#perevod_#{@perevod_id}").remove();

app/views/perevods/edit.html.haml
%h1
  = t('.edit', :default => t("helpers.links.edit"))
  = link_to perevods_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/perevods/index.html.haml
%h1
  = t(:perevods)
  = link_to new_perevod_path, "data-ajax" => "false" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-plus.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t(:new)

.docs-main
  %table#tabl_perevod.tablesaw{"data-minimap" => "", "data-mode" => "swipe", "data-mode-switch" => "", "data-sortable" => "", "data-sortable-switch" => ""}
    %thead
      %tr


        %th{"data-priority" => "1", "data-sortable-col" => ""}= t(:schet_from)

        %th{"data-priority" => "2", "data-sortable-col" => ""}= t(:schet_to)

        %th{"data-priority" => "3", "data-sortable-col" => ""}= t(:rab)

        %th{"data-priority" => "4", "data-sortable-col" => ""}= t(:todate)

        %th{"data-priority" => "5", "data-sortable-col" => ""}= t(:cash)

        %th{"data-priority" => "6", "data-sortable-col" => ""}= t(:comment)
        %th{"data-priority" => "", "data-sortable-col" => ""}
    %tbody
      - @perevods.each do |perevod|
        %tr

          %td
            = perevod.schet_from

          %td
            = perevod.schet_to


          %td
            - if perevod.rab_id
              = perevod.rab.name
          
          %td
            = perevod.todate

          %td
            = perevod.cash

          %td
            = perevod.comment

          %td
            = link_to 'Изменить', edit_perevod_path(perevod), :class => "ui-btn ui-btn-icon-left ui-icon-edit", "data-ajax" => false
            = link_to 'Удалить', perevod, :method => :delete, :data => { :confirm => 'Уверены?' }, :class => "ui-btn ui-btn-icon-left ui-icon-delete", "data-ajax" => false

app/views/perevods/new.html.haml
%h1
  = t('.new', :default => t("helpers.links.new"))
  = link_to perevods_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/perevods/show.html.haml
%h1
  = t('.show', :default => t("helpers.links.show"))
  = link_to perevods_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
    = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/perevods/show.js.haml
// для Модала при создании

// Уведомление 
var perevod_#{@perevod_id}_show = function(){ new PNotify({ title: "Запись #{@perevod.name} создана.", type: 'success', icon: false, hide: true, delay: 1500, buttons: { sticker: false } })};
perevod_#{@perevod_id}_show();

// Добавление в dataTables
// $('#dataTables_perevod').append("#{j render partial: 'perevods/dataTable/index_td', locals: {perevod: @perevod }}");



// Вызов функции Модала
$('#new_perevod_modal').modal_success();