config/routes.rb
Rails.application.routes.draw do
  resources :smena_shtrafs do
    collection { post :import }
  end

  resources :smena_rabs do
    collection { post :import }
  end

  resources :smenas do
    collection { post :import }
  end

  resources :perevods do
    collection { post :import }
  end

  resources :dohods do
    collection { post :import }
  end

  resources :rashods do
    collection { post :import }
  end

  resources :rab_images do
    collection { post :import }
  end

  resources :rabs do
    collection { post :import }
  end

  resources :schets do
    collection { post :import }
  end

  resources :cat_dohods do
    collection { post :import }
  end

  resources :cat_rashods do
    collection { post :import }
  end

  get 'dialog/index'

  resources :perevods

  resources :dohods

  resources :rashods

  resources :rab_images

  resources :rabs

  resources :schets

  resources :cat_dohods

  resources :cat_rashods

  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  devise_for :logins
  resources :logins
  resources :roles
  get 'home/index'
  root "home#index"

end

app/models/login.rb
class Login < ActiveRecord::Base

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :assign_default_role

  has_one :schet

  def assign_default_role
    add_role :reg if self.roles.blank?
  end
  def name
    self.email
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:edit, :update, :destroy]

  def index
    @logins = Login.all
  end
  def show
  end
  def new
    @login = Login.new
  end
  def edit
  end
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  # def update
  #   respond_to do |format|
  #     if @login.update(login_params)
  #       format.html { redirect_to @login, notice: 'Login was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @login }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @login.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update

    if login_params[:password].blank?
      login_params.delete(:password)
      login_params.delete(:password_confirmation)
    end

    # https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-logins-to-edit-their-account-without-providing-a-password
    # successfully_updated = if needs_password?(@login, login_params)
                           #   @login.update(login_params)
                           # else
                           #   @login.update_without_password(login_params)
                           # end

    respond_to do |format|
      # if successfully_updated
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:email, :password, :password_confirmation)
    end
end

app/views/logins/_form.html.haml
- show=false
= form_for @login do |f|
  - if @login.errors.any?
    #error_explanation
      %h2= "#{pluralize(@login.errors.count, "error")} prohibited this login from being saved:"
      %ul
        - @login.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :email, :placeholder => t(:email, :default => t("activerecord.attributes.login.email")), :readonly=>"#{show}"
  .field
    = f.text_field :password, :placeholder => t(:password, :default => t("activerecord.attributes.login.password")), :readonly=>"#{show}"
  .field
    = f.text_field :password_confirmation, :placeholder => t(:password_confirmation), :readonly=>"#{show}"
  .actions
    - if not show
      = f.submit t('.save', :default => t("helpers.links.save")), "data-iconpos" => "right", "data-icon" => "check", :class=>"ui-btn ui-icon-check ui-shadow ui-corner-all ui-btn-icon-right ui-btn-inline", :readonly=>"#{show}"

app/views/logins/edit.html.haml
%h1
  = t('.edit', :default => t("helpers.links.edit"))
  = link_to logins_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"} Назад

.ui-content{:role => "main"}
  = render 'form', show: false

app/views/logins/index.html.haml
.docs-main{ "data-inset"=>"true"}
  %h1
    Список пользователей
    = link_to new_login_path do
      .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-plus.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"} Добавить
  %table#table2.tablesaw{"data-minimap" => "", "data-mode" => "swipe", "data-mode-switch" => "", "data-sortable" => "", "data-sortable-switch" => ""}
    %thead
      %tr
        %th{"data-priority" => "persist", "data-sortable-col" => ""} Email
        %th{"data-priority" => "1", "data-sortable-col" => ""} Роли
        %th{"data-priority" => "", "data-sortable-col" => ""}

      -#- @logins.each do |login|
        %tr
          %th{"data-priority" => "persist", "data-sortable-col" => ""}= login.email
    %tbody
      - @logins.each_with_index do |login, ndx2|
        %tr
          %td
            = link_to login_path(login) do 
              = login.email
          %td
            |
            - login.roles.each do |ro|
              = link_to roles_path do 
                = ro.name
              |

          %td
            = link_to 'Изменить', edit_login_path(login), :class => "ui-btn ui-btn-icon-left ui-icon-edit"
            = link_to 'Удалить', login, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "ui-btn ui-btn-icon-left ui-icon-delete"
          

app/views/logins/new.html.haml
%h1
  = t('.new', :default => t("helpers.links.new"))
  = link_to logins_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"} Назад

= render 'form'

app/views/logins/show.html.haml
%h1
  = t (:view)
  = link_to logins_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"} Назад

= render 'form'

/ %p
/   %b Email:
/   = @login.email
/ %p
/   %b Password:
/   = @login.password
/ %p
/   %b Password confirmation:
/   = @login.password_confirmation

-#.jqm-footer{"data-position" => "fixed", "data-role" => "footer", "data-tap-toggle" => "false"}
  %div{"data-role" => "footer"}
    %div{"data-iconpos" => "bottom", "data-role" => "navbar"}
      %ul
        %li
          = link_to logins_path, "data-icon" => "back" do
            Назад
        %li
          %a{"data-icon" => "grid", :href => "/"} Главная
        - if current_login.has_role? :admin or current_login.has_role? :root
          %li
            %a{"data-icon" => "user", :href => "/logins"} Пользователи
          %li
            = link_to "Редактировать", edit_login_path(@login), "data-icon" => "edit"
        %li
          %a{"data-icon" => "gear", "data-ajax" => "false", :href => "/logins/sign_out"} Выход

    