config/routes.rb
Rails.application.routes.draw do
  resources :smena_shtrafs do
    collection { post :import }
  end

  resources :smena_rabs do
    collection { post :import }
  end

  resources :smenas do
    collection { post :import }
  end

  resources :perevods do
    collection { post :import }
  end

  resources :dohods do
    collection { post :import }
  end

  resources :rashods do
    collection { post :import }
  end

  resources :rab_images do
    collection { post :import }
  end

  resources :rabs do
    collection { post :import }
  end

  resources :schets do
    collection { post :import }
  end

  resources :cat_dohods do
    collection { post :import }
  end

  resources :cat_rashods do
    collection { post :import }
  end

  get 'dialog/index'

  resources :perevods

  resources :dohods

  resources :rashods

  resources :rab_images

  resources :rabs

  resources :schets

  resources :cat_dohods

  resources :cat_rashods

  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  devise_for :logins
  resources :logins
  resources :roles
  get 'home/index'
  root "home#index"

end

app/models/smena_rab.rb
class SmenaRab < ActiveRecord::Base

  # extend Enumerize
  # enumerize :some_field, in: [:one, "two", "last"]
  # locale.yml
  # enumerize:
  #   product:
  #     measure:
  #       gramm: "грамм"

  # has_and_belongs_to_many :events

  # audit table changes
  has_paper_trail
  # cattr_reader :per_page
  # @@per_page = 20
  # TODO paste it to Model Scaffold template  
  #cocoon_marker_start
  #cocoon_marker_data
  #cocoon_marker_end
  belongs_to :smena
  belongs_to :rab

  # before_save :do_something

  def self.import(file)
    spread = open_spreadsheet(file)
    spreadsheet = spread.sheet(0)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      smena_rab = find_by_id(row["id"]) || new
      smena_rab.update row.to_hash
      smena_rab.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |smena_rab|
        csv << smena_rab.attributes.values_at(*column_names)
      end
    end
  end

  define_method :name do
    "#{self.smena.name} #{self.rab.name}"
  end

end

app/controllers/smena_rabs_controller.rb
class SmenaRabsController < ApplicationController
  before_action :set_smena_rab, only: [:show, :edit, :update, :destroy]

  def index
    @smena_rabs = SmenaRab.all
    respond_with(@smena_rabs)
  end

  def show
    respond_with(@smena_rab)
  end

  def new
    @smena_rab = SmenaRab.new
    respond_with(@smena_rab)
  end

  def edit
  end

  def create
    @smena_rab = SmenaRab.new(smena_rab_params)
    @smena_rab.save
    respond_with(@smena_rab)
  end

  def update
    @smena_rab.update(smena_rab_params)
    respond_with(@smena_rab)
  end

  def destroy
    @smena_rab.destroy
    respond_with(@smena_rab)
  end

  private
    def set_smena_rab
      @smena_rab = SmenaRab.find(params[:id])
    end

    def smena_rab_params
      params.require(:smena_rab).permit(:smena_id, :rab_id, :allday, :time_start, :time_end)
    end
end

app/views/smena_rabs/_form.html.haml
= form_for @smena_rab, "data-ajax" => false do |f|
  - if @smena_rab.errors.any?
    #error_explanation
      %h2= "#{pluralize(@smena_rab.errors.count, "error")} prohibited this rab from being saved:"
      %ul
        - @smena_rab.errors.full_messages.each do |msg|
          %li= msg
  %div{ :class=>"smena"}
    .field
      = f.label t(:smena)
      = collection_select(:smena_rab, :smena_id, Smena.all, :id, :name, prompt: true)

  %div{ :class=>"rab"}
    .field
      = f.label t(:rab)
      = collection_select(:smena_rab, :rab_id, Rab.all, :id, :name, prompt: true)

  %div{ :class=>"allday"}
    .field
      = f.label t(:allday)
    = f.check_box :allday

  %div{ :class=>"time_start"}
    .field
      = f.label t(:time_start)
      = f.time_select :time_start

  %div{ :class=>"time_end"}
    .field
      = f.label t(:time_end)
      = f.time_select :time_end

      - 'TABB'
  %div
    .field
      = f.submit t('.save', :default => t("helpers.links.save")), :class => "btn btn-primary", "data-ajax" => false

app/views/smena_rabs/destroy.js.haml
// Удаление

// Уведомление 
var smena_rab_#{@smena_rab_id} = function(){ new PNotify({ title: "Запись #{@smena_rab.name} удалена.", type: 'error', icon: false, hide: true, delay: 1500, buttons: { sticker: false } })};
smena_rab_#{@smena_rab_id}();

// Удаление из dataTables
$("#smena_rab_#{@smena_rab_id}").remove();

app/views/smena_rabs/edit.html.haml
%h1
  = t('.edit', :default => t("helpers.links.edit"))
  = link_to smena_rabs_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/smena_rabs/index.html.haml
%h1
  = t(:smena_rabs)
  = link_to new_smena_rab_path, "data-ajax" => "false" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-plus.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t(:new)

.docs-main
  %table#tabl_smena_rab.tablesaw{"data-minimap" => "", "data-mode" => "swipe", "data-mode-switch" => "", "data-sortable" => "", "data-sortable-switch" => ""}
    %thead
      %tr


        %th{"data-priority" => "1", "data-sortable-col" => ""}= t(:smena)

        %th{"data-priority" => "2", "data-sortable-col" => ""}= t(:rab)

        %th{"data-priority" => "3", "data-sortable-col" => ""}= t(:allday)

        %th{"data-priority" => "4", "data-sortable-col" => ""}= t(:time_start)

        %th{"data-priority" => "5", "data-sortable-col" => ""}= t(:time_end)
        %th{"data-priority" => "", "data-sortable-col" => ""}
    %tbody
      - @smena_rabs.each do |smena_rab|
        %tr


          %td
            - if smena_rab.smena_id
              = smena_rab.smena.name
          

          %td
            - if smena_rab.rab_id
              = smena_rab.rab.name
          

          %td
            = smena_rab.allday ? "Да" : "Нет"
          
          %td
            = smena_rab.time_start

          %td
            = smena_rab.time_end

          %td
            = link_to 'Изменить', edit_smena_rab_path(smena_rab), :class => "ui-btn ui-btn-icon-left ui-icon-edit", "data-ajax" => false
            = link_to 'Удалить', smena_rab, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "ui-btn ui-btn-icon-left ui-icon-delete", "data-ajax" => false

app/views/smena_rabs/new.html.haml
%h1
  = t('.new', :default => t("helpers.links.new"))
  = link_to smena_rabs_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/smena_rabs/show.html.haml
%h1
  = t('.show', :default => t("helpers.links.show"))
  = link_to smena_rabs_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
    = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/smena_rabs/show.js.haml
// для Модала при создании

// Уведомление 
var smena_rab_#{@smena_rab_id}_show = function(){ new PNotify({ title: "Запись #{@smena_rab.name} создана.", type: 'success', icon: false, hide: true, delay: 1500, buttons: { sticker: false } })};
smena_rab_#{@smena_rab_id}_show();

// Добавление в dataTables
// $('#dataTables_smena_rab').append("#{j render partial: 'smena_rabs/dataTable/index_td', locals: {smena_rab: @smena_rab }}");



// Вызов функции Модала
$('#new_smena_rab_modal').modal_success();