config/routes.rb
Rails.application.routes.draw do
  resources :smena_shtrafs do
    collection { post :import }
  end

  resources :smena_rabs do
    collection { post :import }
  end

  resources :smenas do
    collection { post :import }
  end

  resources :perevods do
    collection { post :import }
  end

  resources :dohods do
    collection { post :import }
  end

  resources :rashods do
    collection { post :import }
  end

  resources :rab_images do
    collection { post :import }
  end

  resources :rabs do
    collection { post :import }
  end

  resources :schets do
    collection { post :import }
  end

  resources :cat_dohods do
    collection { post :import }
  end

  resources :cat_rashods do
    collection { post :import }
  end

  get 'dialog/index'

  resources :perevods

  resources :dohods

  resources :rashods

  resources :rab_images

  resources :rabs

  resources :schets

  resources :cat_dohods

  resources :cat_rashods

  resources :charts do
    collection do
      get 'basic_line'
      get 'line_ajax'
      get 'line_labels'
    end
  end

  devise_for :logins
  resources :logins
  resources :roles
  get 'home/index'
  root "home#index"

end

app/models/cat_rashod.rb
class CatRashod < ActiveRecord::Base
  has_many :rashods
  # include TheSortableTree::Scopes
  # acts_as_nested_set

  # include FriendlyId
  # friendly_id :title, :use => [:slugged, :simple_i18n]

  # extend Enumerize
  # enumerize :some_field, in: [:one, "two", "last"]
  # locale.yml
  # enumerize:
  #   product:
  #     measure:
  #       gramm: "грамм"

  # has_and_belongs_to_many :events

  # audit table changes
  has_paper_trail
  # cattr_reader :per_page
  # @@per_page = 20
  # TODO paste it to Model Scaffold template  
  #cocoon_marker_start
  #cocoon_marker_data
  #cocoon_marker_end

  # before_save :do_something

  def self.import(file)
    spread = open_spreadsheet(file)
    spreadsheet = spread.sheet(0)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      cat_rashod = find_by_id(row["id"]) || new
      cat_rashod.update row.to_hash
      cat_rashod.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Roo::Csv.new(file.path)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |cat_rashod|
        csv << cat_rashod.attributes.values_at(*column_names)
      end
    end
  end


end

app/controllers/cat_rashods_controller.rb
class CatRashodsController < ApplicationController
  before_action :set_cat_rashod, only: [:show, :edit, :update, :destroy]
  ##before_action :redirect_tor

  def index
    @cat_rashods = CatRashod.all
    respond_with(@cat_rashods)
  end

  def show
    respond_with(@cat_rashod)
  end

  def new
    @cat_rashod = CatRashod.new
    respond_with(@cat_rashod)
  end

  def edit
  end

  def create
    @cat_rashod = CatRashod.new(cat_rashod_params)
    @cat_rashod.save
    respond_with @cat_rashod do |format|
      format.html { redirect_to root_path }
    end
  end

  def update
    @cat_rashod.update(cat_rashod_params)
    respond_with @cat_rashod do |format|
      format.html { redirect_to root_path }
    end
  end

  def destroy
    @cat_rashod.destroy
    respond_with @cat_rashod do |format|
      format.html { redirect_to root_path }
    end
  end

  private
    def set_cat_rashod
      @cat_rashod = CatRashod.find(params[:id])
    end

    def cat_rashod_params
      params.require(:cat_rashod).permit(:name, :odin)
    end

    def redirect_tor
      respond_to do |format|
        format.html {redirect_to root_path}
        #format.js {render :js => "window.location.href='"+root_path+"'"} if params[:q].present?
      end
    end


end

app/views/cat_rashods/_form.html.haml
= form_for @cat_rashod, "data-ajax" => false do |f|
  - if @cat_rashod.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cat_rashod.errors.count, "error")} prohibited this rab from being saved:"
      %ul
        - @cat_rashod.errors.full_messages.each do |msg|
          %li= msg
  %div{ :class=>"name"}
    .field
      = f.label t(:name)
      = f.text_field :name, :required=>""

    .field
      = f.label "По умолчанию"
      = f.check_box :odin, "data-role"=>"flipswitch"

      - 'TABB'
  %div
    .field
      = f.submit t('.save', :default => t("helpers.links.save")), :class => "btn btn-primary", "data-ajax" => false

app/views/cat_rashods/destroy.js.haml
// Удаление

// Уведомление 
var cat_rashod_#{@cat_rashod_id} = function(){ new PNotify({ title: "Запись #{@cat_rashod.name} удалена.", type: 'error', icon: false, hide: true, delay: 1500, buttons: { sticker: false } })};
cat_rashod_#{@cat_rashod_id}();

// Удаление из dataTables
$("#cat_rashod_#{@cat_rashod_id}").remove();

app/views/cat_rashods/edit.html.haml
%h1
  = t('.edit', :default => t("helpers.links.edit"))
  = link_to cat_rashods_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/cat_rashods/index.html.haml
%h1
  = t(:cat_rashods)
  = link_to new_cat_rashod_path, "data-ajax" => "false" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-plus.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t(:new)

.docs-main
  %table#tabl_cat_rashod.tablesaw{"data-minimap" => "", "data-mode" => "swipe", "data-mode-switch" => "", "data-sortable" => "", "data-sortable-switch" => ""}
    %thead
      %tr


        %th{"data-priority" => "1", "data-sortable-col" => ""}= t(:name)
        %th{"data-priority" => "", "data-sortable-col" => ""}
    %tbody
      - @cat_rashods.each do |cat_rashod|
        %tr


          %td
            = link_to cat_rashod do
              = cat_rashod.name
          %td
            = link_to 'Изменить', edit_cat_rashod_path(cat_rashod), :class => "ui-btn ui-btn-icon-left ui-icon-edit", "data-ajax" => false
            = link_to 'Удалить', cat_rashod, :method => :delete, :data => { :confirm => 'Уверены?' }, :class => "ui-btn ui-btn-icon-left ui-icon-delete", "data-ajax" => false

app/views/cat_rashods/new.html.haml
%h1
  = t('.new', :default => t("helpers.links.new"))
  = link_to cat_rashods_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
      = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/cat_rashods/show.html.haml
%h1
  = t('.show', :default => t("helpers.links.show"))
  = link_to cat_rashods_path, "data-icon" => "back" do
    .ui-shadow.ui-btn.ui-corner-all.ui-btn-inline.ui-icon-back.ui-btn-icon-notext.ui-btn-b{"data-theme" => "b", "data-ajax"=>"false", :style=>"float:right;"}
    = t('.back', :default => t("helpers.links.back"))
= render 'form'

app/views/cat_rashods/show.js.haml
// для Модала при создании

// Уведомление 
var cat_rashod_#{@cat_rashod_id}_show = function(){ new PNotify({ title: "Запись #{@cat_rashod.name} создана.", type: 'success', icon: false, hide: true, delay: 1500, buttons: { sticker: false } })};
cat_rashod_#{@cat_rashod_id}_show();

// Добавление в dataTables
// $('#dataTables_cat_rashod').append("#{j render partial: 'cat_rashods/dataTable/index_td', locals: {cat_rashod: @cat_rashod }}");



// Вызов функции Модала
$('#new_cat_rashod_modal').modal_success();